version: '3.1'

volumes:
  database:
    driver: local

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    container_name: prisma_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: turborepo
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - database:/var/lib/mysql

